18 refactoring
JaoodxD/bin-packing pull request #21
Opened 2024-03-06 13:53 UTC by evgeniy-shpyra

2024-03-06 15:50 UTC, JaoodxD requested changes

2024-03-06 15:50 UTC, JaoodxD commented on example.js
> +  if (!parentBin) throw new Error('Can\'t calculate a dimensions')
```suggestion
  if (!parentBin) throw new Error('Cannot calculate group dimensions')
```

2024-03-06 15:50 UTC, JaoodxD commented on experiments/compose.js
> +const composeTheSame = (item, { maxCount }) => {
```suggestion
const composeTheSame = (item, { maxCount } = {}) => {

2024-03-06 15:50 UTC, JaoodxD commented on example.js
> +  if (!parentBin) throw new Error("Can't calculate a dimensions");
```suggestion
if (!parentBin) throw new Error('Cannot calculate group dimensions')
```

2024-03-06 15:50 UTC, JaoodxD commented on experiments/compose.js
> +        : maxCount
Complex ternary should be simplified or rewrited

2024-03-06 15:50 UTC, JaoodxD commented on experiments/compose.js
> +const composeTheDifferent = (items, { maxCount }) => {
```suggestion
const composeTheDifferent = (items, { maxCount } = {}) => {

2024-03-06 15:50 UTC, JaoodxD commented on experiments/compose.js
> +      groups.push([...subGroup])
```suggestion
      groups.push(subGroup)
```

2024-03-06 15:50 UTC, JaoodxD commented on experiments/compose.js
> +      groups.push([...subGroup])
Unnecessary array copy

2024-03-06 15:50 UTC, JaoodxD commented on experiments/compose.js
> +  if (Array.isArray(items)) { for (const item of items) volume += getGroupVolume(item) }
Too complicated one liner

2024-03-06 15:50 UTC, JaoodxD commented on experiments/compose.js
> +  let volume = 0
```suggestion
  let totalVolume = 0
```

2024-03-06 15:50 UTC, JaoodxD commented on experiments/compose.js
> +  for (const key in items) {
```suggestion
  for (const key in items) {
    const volume = items[key].w * items[key].h * items[key].d
    const count = items[key].count || 1
    totalVolume += volume * count
  }
  ```

2024-03-07 08:09 UTC, evgeniy-shpyra commented
fixed and add tests for packer.pack

2024-03-10 16:10 UTC, JaoodxD requested changes

2024-03-10 16:10 UTC, JaoodxD commented on test/compose.test.js
> +  assert.equal(712, volume)
magic number 712. Not obvious where it comes from.

2024-03-10 16:10 UTC, JaoodxD commented on test/compose.test.js
> +  assert.equal(7424, volume)
magic number

2024-03-10 16:10 UTC, JaoodxD commented on test/compose.test.js
> +  assert.equal(19823, volume)
magic number

2024-03-10 16:10 UTC, JaoodxD commented on test/compose.test.js
> +  assert.deepEqual([expectedItems], ...composedData)
Array of arrays `[expectedItems]` is intended?

2024-03-10 16:10 UTC, JaoodxD commented on test/main.test.js
> +  expectedDim.sort((a, b) => a - b)
What a purpose to sort hard-coded array?

2024-03-10 16:10 UTC, JaoodxD commented on test/main.test.js
> +  expectedDim.sort((a, b) => a - b)
Sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/main.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/main.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/main.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/main.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/packer.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/packer.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/packer.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/packer.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/packer.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-10 16:10 UTC, JaoodxD commented on test/packer.test.js
> +  expectedDim.sort((a, b) => a - b)
sort purpose?

2024-03-11 07:26 UTC, evgeniy-shpyra commented on test/compose.test.js
> +  assert.deepEqual([expectedItems], ...composedData)
yes

2024-03-11 10:06 UTC, JaoodxD approved these changes
lgtm

2024-03-11 10:07 UTC, merged